### ISSUE TITLE
Padrão de roteamento

### ISSUE THREAD

**Issue by evandresilva** [Angola-Api/Angola-Api#19]
Saudações,
Ainda sobre práticas de routing a API devia ter um standard, ou seja se os endpoints estão uns em inglês e outros em português.

Ex.: https://angolaapi.herokuapp.com/api/v1/geography/county?provincia=Malanje

Correcto : https://angolaapi.herokuapp.com/api/v1/geography/county?province=Malanje

**Comment by gentildpinto** [comment]
E também é uma boa prática manter o substantivo/recurso no plural.

Ex: `/counties` ao invés de `/county`

**Comment by evandresilva** [comment]
Exato

**Comment by Paulo-Lopes-Estevao** [comment]
Essa ISSUE foi dada continuidade https://github.com/Angola-Api/Angola-Api/issues/55

Tambem relevante o comentário de Gentil https://github.com/Angola-Api/Angola-Api/issues/19#issuecomment-801758153
