### ISSUE TITLE
Problema com o Cors

### ISSUE THREAD

**Issue by julianasoba** [Angola-Api/Angola-Api#26]
Juliana Soba, e aproveito parabenizar o projecto. Estou usando a vossa API para o meu projecto final, e estou tendo problemas de CORS no consumo. A mensagem retorna dizendo que: Acess to fetch at "link da api" from "meu localhost" has been blocked by CORS. Pode dar uma olhadela no UseCors e ver como está a definição de acesso? Por favor.

Super precisando da vossa ajuda.

**Comment by julianasoba** [comment]
> Olá, muito obrigado! O primeiro erro a gente nunca esquece! Vamos trabalhar com bastante afinco para supera-lo.. | Hello thank you so much! The first mistake we never forget! We will work with great pride to overcome it..

Boas, esperando um sinal.

**Comment by ek1mb4** [comment]
### **Enquanto a equipa de desenvolvimento não responde....**

**@JulianaSobaJava que parte da API estás a utilizar no teu projecto?**

- Se forem as validações enquanto não respondem , a alternativa é usares as expressões regulares que eles têm no projecto e consegues o que queres. 

**Exemplo:**
```
export class ValidatePhone implements IvalidatePhone {
  validate(phone: string): boolean {
    return /^(\+244)\d{9}$/.test(phone);
  }
}
```

- Se forem as taxas tenta usar este endpoint  do site do BNA, executa no browser e testei num frontend Angular e permite execução pública talvez porque é um get os domínios não estão a ser filtrado:

      https://www.bna.ao/service/rest/taxas/get/taxa/referencia?moeda=usd&tipocambio=g

O restante dos parâmetros podes verificar nas requsições do site deles (BNA).

- Se forem os dados das províncias e munícipios, eu baixei o json, usei a mesma interface e inseri numa base de dados usando NodeJS ou podes também fazer conversão dos objectos e crias uma query e já está. 

É muito trabalho mas consegues avançar com o teu projecto.

**Comment by gentildpinto** [comment]
@ek1mb4 que relação isso tem com o CORS?

**Comment by ek1mb4** [comment]
> @ek1mb4 que relação isso tem com o CORS?
Absolutamente nenhuma. Se verificares, o bot do Github é que está a responder cada vez que um novo problema é reportado. Enquanto a equipa de desenvolvimento demora a responder, eu sugeri uma alternativa para ela utilizar no projecto dela. Não há necessidade de aguardar pelo CORs para fazer validação de número de telefone por exemplo.
O problema dos projectos Open Source nos nossos dias é a falta de desenvolvedores que tenham tempo a mais e se dediquem sem remuneração.

**Comment by gentildpinto** [comment]
@ek1mb4 isso é bem verdade

**Comment by gentildpinto** [comment]
Este projeto parece morto 😅 :/

**Comment by julianasoba** [comment]
Olá, pessoal. Tive que optar por criar um ficheiro .json. E estou fazendo a requisição de forma local mesmo.

**Comment by julianasoba** [comment]
> ### **Enquanto a equipa de desenvolvimento não responde....**
> **@JulianaSobaJava que parte da API estás a utilizar no teu projecto?**
> 
> * Se forem as validações enquanto não respondem , a alternativa é usares as expressões regulares que eles têm no projecto e consegues o que queres.
> 
> **Exemplo:**
> 
> ```
> export class ValidatePhone implements IvalidatePhone {
>   validate(phone: string): boolean {
>     return /^(\+244)\d{9}$/.test(phone);
>   }
> }
> ```
> 
> * Se forem as taxas tenta usar este endpoint  do site do BNA, executa no browser e testei num frontend Angular e permite execução pública talvez porque é um get os domínios não estão a ser filtrado:
>   ```
>   https://www.bna.ao/service/rest/taxas/get/taxa/referencia?moeda=usd&tipocambio=g
>   ```
> 
> O restante dos parâmetros podes verificar nas requsições do site deles (BNA).
> 
> * Se forem os dados das províncias e munícipios, eu baixei o json, usei a mesma interface e inseri numa base de dados usando NodeJS ou podes também fazer conversão dos objectos e crias uma query e já está.
> 
> É muito trabalho mas consegues avançar com o teu projecto.

Já consegui. Optei por não usar a API, peguei todas as informações que estava precisando e botei em um ficheiro province.json, estou faazendo a requisição de forma local mesmo. Valeu!

**Comment by ek1mb4** [comment]
> Este projeto parece morto 😅 :/

So vai morrer se nós deixarmos, eu estou a estudar estas cenas para fazer o fork e contribuir na manutenção do projecto. Alguém começou então o resto da comunidade deve dar sequência. Em termos de open source em Angola contribuimos nada, se compararmos com os Naijas, Ganenses e Kenianos por exemplo.

**Comment by gentildpinto** [comment]
> > Este projeto parece morto sweat_smile :/
> 
> So vai morrer se nós deixarmos, eu estou a estudar estas cenas para fazer o fork e contribuir na manutenção do projecto. Alguém começou então o resto da comunidade deve dar sequência. Em termos de open source em Angola contribuimos nada, se compararmos com os Naijas, Ganenses e Kenianos por exemplo.

O problema é que o responsáveis do projecto sumiram.
Você pode até contribuir, mas quem vai aprovar as PR's e responder as issues? :/
