### ISSUE TITLE
Validação de Número de Telefone

### ISSUE THREAD

**Issue by luiscaputo** [Angola-Api/Angola-Api#28]
A API para validação de número de telefone, não está afinada, por exemplo, em minha aplicação consumo a vossa API e quando é passado o seguinte como parâmetro: _https://angolaapi.herokuapp.com/api/v1/validate/phone/+244975323281_ a api simplesmente retorna duzento, nota que *97* não está registrado na rede de Angola, sugestão validar os números registrados na rede daqui, são eles: 
- 91...
- 92...
- 93...
- 94...
- 95...
- 99...

Atenciosamente, 
_Luís Afonso Caputo_

**Comment by Paulo-Lopes-Estevao** [comment]
Obrigado pela nota, foi resolvida https://github.com/Angola-Api/Angola-Api/pull/36
