### ISSUE TITLE
Problema a executar as routas

### ISSUE THREAD

**Issue by Angleu** [Angola-Api/Angola-Api#30]
Parece que o vosso servidor está em baixo e é impossível fazer consulta na vossa api.
Aconselho a verificarem o log do heroku, ou caso vocês não ficaram a saber o heroku mudou os planos, e já não existe serviços free por parte deles.
Aconselho a migrarem a api para **https://render.com/**
Pode haver lentidão quando o servidor fica muito tempo inativo, mas depois restabelece.
Comecei a dar uma olhada na vossa iniciatica, e pretendo contribuir também, após o serviço estiver no ar eu vou submeter uma nova feature para consultas de NIF.

<img width="1680" alt="Screenshot 2023-01-10 at 22 56 49" src="https://user-images.githubusercontent.com/67520501/211671900-58240d0d-8e03-40dc-bf46-abbc9345b3a0.png">

**Comment by CristinoCg** [comment]
> Parece que o vosso servidor está em baixo e é impossível fazer consulta na vossa api. Aconselho a verificarem o log do heroku, ou caso vocês não ficaram a saber o heroku mudou os planos, e já não existe serviços free por parte deles. Aconselho a migrarem a api para **https://render.com/** Pode haver lentidão quando o servidor fica muito tempo inativo, mas depois restabelece. Comecei a dar uma olhada na vossa iniciatica, e pretendo contribuir também, após o serviço estiver no ar eu vou submeter uma nova feature para consultas de NIF.
> 
> <img alt="Screenshot 2023-01-10 at 22 56 49" width="1680" src="https://user-images.githubusercontent.com/67520501/211671900-58240d0d-8e03-40dc-bf46-abbc9345b3a0.png">

[edit]:Eu não faço parte do projecto, mas como disseste uma mudança na hospedagem seria a solucação. Eu pensei em fazê-lo mas o projecto é feito em Js e Ts, e eu ainda não sou bom nessas duas linguagens...

**Comment by ghost** [comment]
## Netlify
Sugiro que mudem para [Netlify](https://www.netlify.com/pricing/) .

**Comment by luteroelavoco** [comment]
Gentxeee, quem poder fazer essa migração agradeço.

**Comment by Paulo-Lopes-Estevao** [comment]
Essa ISSUE já foi resolvida https://angolaapi.onrender.com
