### ISSUE TITLE
Erro:  Endereço inacessível angolaapi.herokuapp.com

### ISSUE THREAD

**Issue by Paulo-Lopes-Estevao** [Angola-Api/Angola-Api#35]
O endereço encontra-se indisponivel para requisições `https://angolaapi.herokuapp.com`

Existe uma PR com sugestão https://github.com/Angola-Api/Angola-Api/pull/33

Heroku deixou de dar suporte aos planos free em 28 November 2022 [Removal of Heroku Free Product Plans](https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq)

**Alternativa :**
- [Render](https://render.com/)
- [Fly](https://fly.io/)
- [Railway](https://railway.app/)
...

**Comment by carl0smat3us** [comment]
🤌👍

**Comment by Paulo-Lopes-Estevao** [comment]
Essa ISSUE já foi resolvida novo endereço https://angolaapi.onrender.com
