### ISSUE TITLE
Não consigo rodar o projeto na minha máquina.

### ISSUE THREAD

**Issue by epifaniofrancisco** [Angola-Api/Angola-Api#45]
Estou a tentar rodar o projeto na minha máquina, mas até agora recebo mensagens de erro no console.

Qual é o jeito correto para rodar esse projeto?

**Comment by Paulo-Lopes-Estevao** [comment]
npm i  - para fazer a instalação dos pacotes
npm run dev - para rodar em desenvolvimento
