### ISSUE TITLE
Erro de tempo limite ao buscar dados da província em endpoint específico

### ISSUE THREAD

**Issue by carl0smat3us** [Angola-Api/Angola-Api#46]
Ao realizar uma solicitação em qualquer endpoint que busca informações relacionadas às regiões do país, tenho encontrado um erro persistente. A mensagem de erro exibida é a seguinte:

```json
{
    "message": "Operação `provincias.findOne()` atingiu o tempo limite de buffer após 10000ms"
}
```
Exemplos de Endpoints:

[/api/v1/geography/county?provincia=Luanda](https://angolaapi.onrender.com/api/v1/geography/county?provincia=Luanda)
[/api/v1/geography/provinces](https://angolaapi.onrender.com/api/v1/geography/provinces)

**Comment by Paulo-Lopes-Estevao** [comment]
Essa issue foi resolvida https://github.com/Angola-Api/Angola-Api/pull/53
