### ISSUE TITLE
fix: resolver problema no filtro de provincia

### ISSUE THREAD

**Issue by Paulo-Lopes-Estevao** [Angola-Api/Angola-Api#55]
Existe uma dependecia com banco de dados mongoDB que deixou de dar suporte ao projeto, por este motivo será necessário separar os dados para uma nova conexão SQLite3 já existente.

https://angolaapi.onrender.comapi/v1/geography/county?provincia=Luanda

Obsevações relavante

 https://github.com/Angola-Api/Angola-Api/issues/19 

> **Nota**: https://github.com/Angola-Api/Angola-Api/issues/19#issuecomment-801758153

segui o exemplo como os dados devem ser retornados - https://github.com/Angola-Api/Angola-Api#exemplo-da-consulta-8

**Comment by felixdomingos1** [comment]
> Existe uma dependecia com banco de dados mongoDB que deixou de dar suporte ao projeto, por este motivo será necessário separar os dados para uma nova conexão SQLite3 já existente.
> 
> https://angolaapi.onrender.comapi/v1/geography/county?provincia=Luanda
> 
> Obsevações relavante
> 
> #19
> 
> > **Nota**: [#19 (comment)](https://github.com/Angola-Api/Angola-Api/issues/19#issuecomment-801758153)
> 
> segui o exemplo como os dados devem ser retornados - https://github.com/Angola-Api/Angola-Api#exemplo-da-consulta-8


> https://angolaapi.onrender.com/api/v1/geography/county?provincia=Luanda
quando acedemos a esta rota encontramos  seguinte
`{
  "message": "Operation `provincias.findOne()` buffering timed out after 10000ms"
}`

**Comment by elisiomualumene** [comment]
@Paulo-Lopes-Estevao  acredito que essa issue já está resolvida

**Comment by Paulo-Lopes-Estevao** [comment]
Essa ISSUE já foi resolvida PR #61 #62
